export enum Rank {
  BinhNhi = "Binh nhì",
  BinhNhat = "Binh nhất",
  HaSi = "Hạ sĩ",
  TrungSi = "Trung sĩ",
  ThuongSi = "Thượng sĩ",
  ThieuUyCN = "Thiếu úy CN",
  TrungUyCN = "Trung úy CN",
  ThuongUyCN = "Thượng úy CN",
  DaiUyCN = "Đại úy CN",
  ThieuTaCN = "Thiếu tá CN",
  TrungTaCN = "Trung tá CN",
  ThuongTaCN = "Thượng tá CN",
  ThieuUy = "Thiếu úy",
  TrungUy = "Trung úy",
  ThuongUy = "Thượng úy",
  DaiUy = "Đại úy",
  ThieuTa = "Thiếu tá",
  TrungTa = "Trung tá",
  ThuongTa = "Thượng tá",
  DaiTa = "Đại tá",
  ThieuTuong = "Thiếu tướng",
  TrungTuong = "Trung tướng",
  ThuongTuong = "Thượng tướng",
  DaiTuong = "Đại tướng",
}
