import {
  SearchOutlined as search,
  DownloadOutlined as download,
  UploadOutlined as upload,
  PlusOutlined as add,
  UserOutlined as user,
  SaveOutlined as save,
  AudioOutlined as mic,
  AudioMutedOutlined as mute,
  SoundOutlined as speaker,
  PauseOutlined as pause,
  CaretRightOutlined as play,
  BarsOutlined as bars,
  RightOutlined as right,
  UpOutlined as up,
  CheckCircleFilled as checkFilled,
  CloseCircleFilled as closeFilled,
  DeleteOutlined as remove,
  MinusOutlined as sub,
  CloseOutlined as close,
  ClockCircleOutlined as clock,
  DownOutlined as down,
  MoreOutlined as more,
  MailOutlined as man,
  FileTextOutlined as file,
  CalendarOutlined as calender,
  PrinterOutlined as printer,
  CopyOutlined as copy,
  EditOutlined as edit,
  RedoOutlined as redo,
  ReloadOutlined as reload,
  CameraOutlined as camera,
  EyeOutlined as eye
} from "@ant-design/icons";
export default {
  search,
  download,
  upload,
  add,
  user,
  save,
  mic,
  mute,
  speaker,
  pause,
  play,
  bars,
  right,
  up,
  calender,
  checkFilled,
  closeFilled,
  remove,
  sub,
  close,
  clock,
  down,
  more,
  man,
  file,
  printer,
  copy,
  edit,
  redo,
  reload,
  camera,
  eye,
};
